@extends('layouts.cart')
@section('content')

<div>



    {{-- <div id="v-w3layouts-0" style="display: block; width: 100%; margin-left: 0px;">
      <vdo id="parentDiv0">
          <vdo id="unitDivWrapper-0" style="height: 450px;">
              <div id="_vdo_ads_player_ai_3944" style="display: block; width: 100%; margin-left: 0px;" class="vdo_content"><img src="payment_archivos/cross.svg" class="cross" id="vdo_ai_cross" style="width: 17px!important; height: 17px!important; top: -8px; right: -8px;">
                  <video-js id="vdo_ai_5367430" muted="true" autoplay="true" playsinline="playsinline" webkit-playsinline="webkit-playsinline" style="transition: none!important; border-radius: 0%!important;" class="vdo-js vjs-default-skin vdo-vjs-custom-skin vdo_ai_5367430-dimensions vjs-controls-enabled vjs-workinghover vjs-v7 vdo-autoplay-disabled vjs-has-started vjs-paused vjs-user-inactive"
                      poster="https://s.vdo.ai/uploads/thumbnails/16394881987561b89ac68dd3d.png" tabindex="-1" role="region" aria-label="Video Player" lang="zxx"><video tabindex="-1" poster="https://s.vdo.ai/uploads/thumbnails/16394881987561b89ac68dd3d.png" class="vjs-tech" style="transition: none!important; border-radius: 0%!important;" webkit-playsinline="true" playsinline="playsinline" autoplay="autoplay"
                          muted="muted" id="vdo_ai_5367430_html5_api" preload="true" src="blob:https://p.w3layouts.com/505edb18-b084-4ab0-b620-6f5576998532"><source src="payment_archivos/16394881987561b89ac68dd3d.m3u8" type="application/x-mpegURL"></video>
                      <div class="vjs-poster" tabindex="-1" aria-disabled="false" style="background-image: url(&quot;https://s.vdo.ai/uploads/thumbnails/16394881987561b89ac68dd3d.png&quot;);"></div>
                      <div class="vjs-text-track-display" aria-live="off" aria-atomic="true">
                          <div style="position: absolute; inset: 0px; margin: 1.5%;"></div>
                      </div>
                      <div class="vjs-loading-spinner" dir="ltr"><span class="vjs-control-text">Video Player is loading.</span></div><button class="vjs-big-play-button" type="button" title="Play Video" aria-disabled="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Play Video</span></button>
                      <div class="vjs-control-bar" dir="ltr"><button class="vjs-play-control vjs-control vjs-button vjs-paused" type="button" title="Play" aria-disabled="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Play</span></button>
                          <div class="vjs-volume-panel vjs-control vjs-volume-panel-vertical"><button class="vjs-mute-control vjs-control vjs-button vjs-vol-0" type="button" title="Unmute" aria-disabled="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Unmute</span></button>
                              <div class="vjs-volume-control vjs-control vjs-volume-vertical">
                                  <div tabindex="0" class="vjs-volume-bar vjs-slider-bar vjs-slider vjs-slider-vertical" role="slider" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" aria-label="Volume Level" aria-live="polite" aria-valuetext="0%">
                                      <div class="vjs-mouse-display">
                                          <div class="vjs-volume-tooltip" aria-hidden="true"></div>
                                      </div>
                                      <div class="vjs-volume-level" style="height: 0%;"><span class="vjs-control-text"></span></div>
                                  </div>
                              </div>
                          </div>
                          <div class="vjs-current-time vjs-time-control vjs-control"><span class="vjs-control-text" role="presentation">Current Time&nbsp;</span><span class="vjs-current-time-display" aria-live="off" role="presentation">0:00</span></div>
                          <div class="vjs-time-control vjs-time-divider" aria-hidden="true">
                              <div><span>/</span></div>
                          </div>
                          <div class="vjs-duration vjs-time-control vjs-control"><span class="vjs-control-text" role="presentation">Duration&nbsp;</span><span class="vjs-duration-display" aria-live="off" role="presentation">50:01</span></div>
                          <div class="vjs-progress-control vjs-control">
                              <div tabindex="0" class="vjs-progress-holder vjs-slider vjs-slider-horizontal" role="slider" aria-valuenow="0.00" aria-valuemin="0" aria-valuemax="100" aria-label="Progress Bar" aria-valuetext="00:00 of 50:01">
                                  <div class="vjs-load-progress" style="width: 1.02%;"><span class="vjs-control-text"><span>Loaded</span>: <span class="vjs-control-text-loaded-percentage">1.02%</span></span>
                                      <div data-start="0" data-end="30.762666" style="left: 0%; width: 100%;"></div>
                                  </div>
                                  <div class="vjs-mouse-display">
                                      <div class="vjs-time-tooltip" aria-hidden="true"></div>
                                  </div>
                                  <div class="vjs-play-progress vjs-slider-bar" aria-hidden="true" style="width: 0%;">
                                      <div class="vjs-time-tooltip" aria-hidden="true" style="right: -35px;">00:00</div>
                                  </div>
                              </div>
                          </div>
                          <div class="vjs-live-control vjs-control vjs-hidden">
                              <div class="vjs-live-display" aria-live="off"><span class="vjs-control-text">Stream Type&nbsp;</span>LIVE</div>
                          </div><button class="vjs-seek-to-live-control vjs-control" type="button" title="Seek to live, currently behind live" aria-disabled="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Seek to live, currently behind live</span><span class="vjs-seek-to-live-text" aria-hidden="true">LIVE</span></button>
                          <div class="vjs-remaining-time vjs-time-control vjs-control"><span class="vjs-control-text" role="presentation">Remaining Time&nbsp;</span><span aria-hidden="true">-</span><span class="vjs-remaining-time-display" aria-live="off" role="presentation">50:01</span></div>
                          <div class="vjs-custom-control-spacer vjs-spacer ">&nbsp;</div>
                          <div class="vjs-playback-rate vjs-menu-button vjs-menu-button-popup vjs-control vjs-button vjs-hidden">
                              <div class="vjs-playback-rate-value" id="vjs-playback-rate-value-label-vdo_ai_5367430_component_1087">1x</div><button class="vjs-playback-rate vjs-menu-button vjs-menu-button-popup vjs-button" type="button" aria-disabled="false" title="Playback Rate" aria-haspopup="true" aria-expanded="false" aria-describedby="vjs-playback-rate-value-label-vdo_ai_5367430_component_1087"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Playback Rate</span></button>
                              <div class="vjs-menu">
                                  <ul class="vjs-menu-content" role="menu"></ul>
                              </div>
                          </div>
                          <div class="vjs-chapters-button vjs-menu-button vjs-menu-button-popup vjs-control vjs-button vjs-hidden"><button class="vjs-chapters-button vjs-menu-button vjs-menu-button-popup vjs-button" type="button" aria-disabled="false" title="Chapters" aria-haspopup="true" aria-expanded="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Chapters</span></button>
                              <div class="vjs-menu">
                                  <ul class="vjs-menu-content" role="menu">
                                      <li class="vjs-menu-title" tabindex="-1">Chapters</li>
                                  </ul>
                              </div>
                          </div>
                          <div class="vjs-descriptions-button vjs-menu-button vjs-menu-button-popup vjs-control vjs-button vjs-hidden"><button class="vjs-descriptions-button vjs-menu-button vjs-menu-button-popup vjs-button" type="button" aria-disabled="false" title="Descriptions" aria-haspopup="true" aria-expanded="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Descriptions</span></button>
                              <div class="vjs-menu">
                                  <ul class="vjs-menu-content" role="menu">
                                      <li class="vjs-menu-item vjs-selected" tabindex="-1" role="menuitemradio" aria-disabled="false" aria-checked="true"><span class="vjs-menu-item-text">descriptions off</span><span class="vjs-control-text" aria-live="polite">, selected</span></li>
                                  </ul>
                              </div>
                          </div>
                          <div class="vjs-subs-caps-button vjs-menu-button vjs-menu-button-popup vjs-control vjs-button vjs-hidden"><button class="vjs-subs-caps-button vjs-menu-button vjs-menu-button-popup vjs-button" type="button" aria-disabled="false" title="Subtitles" aria-haspopup="true" aria-expanded="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Subtitles</span></button>
                              <div class="vjs-menu">
                                  <ul class="vjs-menu-content" role="menu">
                                      <li class="vjs-menu-item vjs-texttrack-settings" tabindex="-1" role="menuitem" aria-disabled="false"><span class="vjs-menu-item-text">subtitles settings</span><span class="vjs-control-text" aria-live="polite">, opens subtitles settings dialog</span></li>
                                      <li class="vjs-menu-item vjs-selected" tabindex="-1" role="menuitemradio" aria-disabled="false" aria-checked="true"><span class="vjs-menu-item-text">subtitles off</span><span class="vjs-control-text" aria-live="polite">, selected</span></li>
                                  </ul>
                              </div>
                          </div>
                          <div class="vjs-audio-button vjs-menu-button vjs-menu-button-popup vjs-control vjs-button vjs-hidden"><button class="vjs-audio-button vjs-menu-button vjs-menu-button-popup vjs-button" type="button" aria-disabled="false" title="Audio Track" aria-haspopup="true" aria-expanded="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Audio Track</span></button>
                              <div class="vjs-menu">
                                  <ul class="vjs-menu-content" role="menu">
                                      <li class="vjs-menu-item vjs-selected vjs-main-menu-item" tabindex="-1" role="menuitemradio" aria-disabled="false" aria-checked="true"><span class="vjs-menu-item-text">default</span><span class="vjs-control-text" aria-live="polite">, selected</span></li>
                                  </ul>
                              </div>
                          </div><button class="vjs-fullscreen-control vjs-control vjs-button" type="button" title="Fullscreen" aria-disabled="false"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Fullscreen</span></button></div>
                      <div class="vjs-error-display vjs-modal-dialog vjs-hidden " tabindex="-1" aria-describedby="vdo_ai_5367430_component_1288_description" aria-hidden="true" aria-label="Modal Window" role="dialog">
                          <p class="vjs-modal-dialog-description vjs-control-text" id="vdo_ai_5367430_component_1288_description">This is a modal window.</p>
                          <div class="vjs-modal-dialog-content" role="document"></div>
                      </div>
                      <div class="vjs-modal-dialog vjs-hidden  vjs-text-track-settings" tabindex="-1" aria-describedby="vdo_ai_5367430_component_1294_description" aria-hidden="true" aria-label="Caption Settings Dialog" role="dialog">
                          <p class="vjs-modal-dialog-description vjs-control-text" id="vdo_ai_5367430_component_1294_description">Beginning of dialog window. Escape will cancel and close the window.</p>
                          <div class="vjs-modal-dialog-content" role="document">
                              <div class="vjs-track-settings-colors">
                                  <fieldset class="vjs-fg-color vjs-track-setting">
                                      <legend id="captions-text-legend-vdo_ai_5367430_component_1294">Text</legend><label id="captions-foreground-color-vdo_ai_5367430_component_1294" class="vjs-label">Color</label><select aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294"><option id="captions-foreground-color-vdo_ai_5367430_component_1294-White" value="#FFF" aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294-White" selected="selected">White</option><option id="captions-foreground-color-vdo_ai_5367430_component_1294-Black" value="#000" aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294-Black">Black</option><option id="captions-foreground-color-vdo_ai_5367430_component_1294-Red" value="#F00" aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294-Red">Red</option><option id="captions-foreground-color-vdo_ai_5367430_component_1294-Green" value="#0F0" aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294-Green">Green</option><option id="captions-foreground-color-vdo_ai_5367430_component_1294-Blue" value="#00F" aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294-Blue">Blue</option><option id="captions-foreground-color-vdo_ai_5367430_component_1294-Yellow" value="#FF0" aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294-Yellow">Yellow</option><option id="captions-foreground-color-vdo_ai_5367430_component_1294-Magenta" value="#F0F" aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294-Magenta">Magenta</option><option id="captions-foreground-color-vdo_ai_5367430_component_1294-Cyan" value="#0FF" aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294 captions-foreground-color-vdo_ai_5367430_component_1294-Cyan">Cyan</option></select>
                                      <span class="vjs-text-opacity vjs-opacity"><label id="captions-foreground-opacity-vdo_ai_5367430_component_1294" class="vjs-label">Transparency</label><select aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-opacity-vdo_ai_5367430_component_1294"><option id="captions-foreground-opacity-vdo_ai_5367430_component_1294-Opaque" value="1" aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-opacity-vdo_ai_5367430_component_1294 captions-foreground-opacity-vdo_ai_5367430_component_1294-Opaque" selected="selected">Opaque</option><option id="captions-foreground-opacity-vdo_ai_5367430_component_1294-SemiTransparent" value="0.5" aria-labelledby="captions-text-legend-vdo_ai_5367430_component_1294 captions-foreground-opacity-vdo_ai_5367430_component_1294 captions-foreground-opacity-vdo_ai_5367430_component_1294-SemiTransparent">Semi-Transparent</option></select></span>
                                  </fieldset>
                                  <fieldset class="vjs-bg-color vjs-track-setting">
                                      <legend id="captions-background-vdo_ai_5367430_component_1294">Background</legend><label id="captions-background-color-vdo_ai_5367430_component_1294" class="vjs-label">Color</label><select aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294"><option id="captions-background-color-vdo_ai_5367430_component_1294-Black" value="#000" aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294-Black" selected="selected">Black</option><option id="captions-background-color-vdo_ai_5367430_component_1294-White" value="#FFF" aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294-White">White</option><option id="captions-background-color-vdo_ai_5367430_component_1294-Red" value="#F00" aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294-Red">Red</option><option id="captions-background-color-vdo_ai_5367430_component_1294-Green" value="#0F0" aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294-Green">Green</option><option id="captions-background-color-vdo_ai_5367430_component_1294-Blue" value="#00F" aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294-Blue">Blue</option><option id="captions-background-color-vdo_ai_5367430_component_1294-Yellow" value="#FF0" aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294-Yellow">Yellow</option><option id="captions-background-color-vdo_ai_5367430_component_1294-Magenta" value="#F0F" aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294-Magenta">Magenta</option><option id="captions-background-color-vdo_ai_5367430_component_1294-Cyan" value="#0FF" aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294 captions-background-color-vdo_ai_5367430_component_1294-Cyan">Cyan</option></select>
                                      <span class="vjs-bg-opacity vjs-opacity"><label id="captions-background-opacity-vdo_ai_5367430_component_1294" class="vjs-label">Transparency</label><select aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-opacity-vdo_ai_5367430_component_1294"><option id="captions-background-opacity-vdo_ai_5367430_component_1294-Opaque" value="1" aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-opacity-vdo_ai_5367430_component_1294 captions-background-opacity-vdo_ai_5367430_component_1294-Opaque" selected="selected">Opaque</option><option id="captions-background-opacity-vdo_ai_5367430_component_1294-SemiTransparent" value="0.5" aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-opacity-vdo_ai_5367430_component_1294 captions-background-opacity-vdo_ai_5367430_component_1294-SemiTransparent">Semi-Transparent</option><option id="captions-background-opacity-vdo_ai_5367430_component_1294-Transparent" value="0" aria-labelledby="captions-background-vdo_ai_5367430_component_1294 captions-background-opacity-vdo_ai_5367430_component_1294 captions-background-opacity-vdo_ai_5367430_component_1294-Transparent">Transparent</option></select></span>
                                  </fieldset>
                                  <fieldset class="vjs-window-color vjs-track-setting">
                                      <legend id="captions-window-vdo_ai_5367430_component_1294">Window</legend><label id="captions-window-color-vdo_ai_5367430_component_1294" class="vjs-label">Color</label><select aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294"><option id="captions-window-color-vdo_ai_5367430_component_1294-Black" value="#000" aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294-Black" selected="selected">Black</option><option id="captions-window-color-vdo_ai_5367430_component_1294-White" value="#FFF" aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294-White">White</option><option id="captions-window-color-vdo_ai_5367430_component_1294-Red" value="#F00" aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294-Red">Red</option><option id="captions-window-color-vdo_ai_5367430_component_1294-Green" value="#0F0" aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294-Green">Green</option><option id="captions-window-color-vdo_ai_5367430_component_1294-Blue" value="#00F" aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294-Blue">Blue</option><option id="captions-window-color-vdo_ai_5367430_component_1294-Yellow" value="#FF0" aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294-Yellow">Yellow</option><option id="captions-window-color-vdo_ai_5367430_component_1294-Magenta" value="#F0F" aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294-Magenta">Magenta</option><option id="captions-window-color-vdo_ai_5367430_component_1294-Cyan" value="#0FF" aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294 captions-window-color-vdo_ai_5367430_component_1294-Cyan">Cyan</option></select>
                                      <span class="vjs-window-opacity vjs-opacity"><label id="captions-window-opacity-vdo_ai_5367430_component_1294" class="vjs-label">Transparency</label><select aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-opacity-vdo_ai_5367430_component_1294"><option id="captions-window-opacity-vdo_ai_5367430_component_1294-Transparent" value="0" aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-opacity-vdo_ai_5367430_component_1294 captions-window-opacity-vdo_ai_5367430_component_1294-Transparent" selected="selected">Transparent</option><option id="captions-window-opacity-vdo_ai_5367430_component_1294-SemiTransparent" value="0.5" aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-opacity-vdo_ai_5367430_component_1294 captions-window-opacity-vdo_ai_5367430_component_1294-SemiTransparent">Semi-Transparent</option><option id="captions-window-opacity-vdo_ai_5367430_component_1294-Opaque" value="1" aria-labelledby="captions-window-vdo_ai_5367430_component_1294 captions-window-opacity-vdo_ai_5367430_component_1294 captions-window-opacity-vdo_ai_5367430_component_1294-Opaque">Opaque</option></select></span>
                                  </fieldset>
                              </div>
                              <div class="vjs-track-settings-font">
                                  <fieldset class="vjs-font-percent vjs-track-setting">
                                      <legend id="captions-font-size-vdo_ai_5367430_component_1294" class="">Font Size</legend><select aria-labelledby="captions-font-size-vdo_ai_5367430_component_1294"><option id="captions-font-size-vdo_ai_5367430_component_1294-50" value="0.50" aria-labelledby="captions-font-size-vdo_ai_5367430_component_1294 captions-font-size-vdo_ai_5367430_component_1294-50">50%</option><option id="captions-font-size-vdo_ai_5367430_component_1294-75" value="0.75" aria-labelledby="captions-font-size-vdo_ai_5367430_component_1294 captions-font-size-vdo_ai_5367430_component_1294-75">75%</option><option id="captions-font-size-vdo_ai_5367430_component_1294-100" value="1.00" aria-labelledby="captions-font-size-vdo_ai_5367430_component_1294 captions-font-size-vdo_ai_5367430_component_1294-100" selected="selected">100%</option><option id="captions-font-size-vdo_ai_5367430_component_1294-125" value="1.25" aria-labelledby="captions-font-size-vdo_ai_5367430_component_1294 captions-font-size-vdo_ai_5367430_component_1294-125">125%</option><option id="captions-font-size-vdo_ai_5367430_component_1294-150" value="1.50" aria-labelledby="captions-font-size-vdo_ai_5367430_component_1294 captions-font-size-vdo_ai_5367430_component_1294-150">150%</option><option id="captions-font-size-vdo_ai_5367430_component_1294-175" value="1.75" aria-labelledby="captions-font-size-vdo_ai_5367430_component_1294 captions-font-size-vdo_ai_5367430_component_1294-175">175%</option><option id="captions-font-size-vdo_ai_5367430_component_1294-200" value="2.00" aria-labelledby="captions-font-size-vdo_ai_5367430_component_1294 captions-font-size-vdo_ai_5367430_component_1294-200">200%</option><option id="captions-font-size-vdo_ai_5367430_component_1294-300" value="3.00" aria-labelledby="captions-font-size-vdo_ai_5367430_component_1294 captions-font-size-vdo_ai_5367430_component_1294-300">300%</option><option id="captions-font-size-vdo_ai_5367430_component_1294-400" value="4.00" aria-labelledby="captions-font-size-vdo_ai_5367430_component_1294 captions-font-size-vdo_ai_5367430_component_1294-400">400%</option></select></fieldset>
                                  <fieldset class="vjs-edge-style vjs-track-setting">
                                      <legend id="vdo_ai_5367430_component_1294" class="">Text Edge Style</legend><select aria-labelledby="vdo_ai_5367430_component_1294"><option id="vdo_ai_5367430_component_1294-None" value="none" aria-labelledby="vdo_ai_5367430_component_1294 vdo_ai_5367430_component_1294-None" selected="selected">None</option><option id="vdo_ai_5367430_component_1294-Raised" value="raised" aria-labelledby="vdo_ai_5367430_component_1294 vdo_ai_5367430_component_1294-Raised">Raised</option><option id="vdo_ai_5367430_component_1294-Depressed" value="depressed" aria-labelledby="vdo_ai_5367430_component_1294 vdo_ai_5367430_component_1294-Depressed">Depressed</option><option id="vdo_ai_5367430_component_1294-Uniform" value="uniform" aria-labelledby="vdo_ai_5367430_component_1294 vdo_ai_5367430_component_1294-Uniform">Uniform</option><option id="vdo_ai_5367430_component_1294-Dropshadow" value="dropshadow" aria-labelledby="vdo_ai_5367430_component_1294 vdo_ai_5367430_component_1294-Dropshadow">Dropshadow</option></select></fieldset>
                                  <fieldset class="vjs-font-family vjs-track-setting">
                                      <legend id="captions-font-family-vdo_ai_5367430_component_1294" class="">Font Family</legend><select aria-labelledby="captions-font-family-vdo_ai_5367430_component_1294"><option id="captions-font-family-vdo_ai_5367430_component_1294-ProportionalSansSerif" value="proportionalSansSerif" aria-labelledby="captions-font-family-vdo_ai_5367430_component_1294 captions-font-family-vdo_ai_5367430_component_1294-ProportionalSansSerif" selected="selected">Proportional Sans-Serif</option><option id="captions-font-family-vdo_ai_5367430_component_1294-MonospaceSansSerif" value="monospaceSansSerif" aria-labelledby="captions-font-family-vdo_ai_5367430_component_1294 captions-font-family-vdo_ai_5367430_component_1294-MonospaceSansSerif">Monospace Sans-Serif</option><option id="captions-font-family-vdo_ai_5367430_component_1294-ProportionalSerif" value="proportionalSerif" aria-labelledby="captions-font-family-vdo_ai_5367430_component_1294 captions-font-family-vdo_ai_5367430_component_1294-ProportionalSerif">Proportional Serif</option><option id="captions-font-family-vdo_ai_5367430_component_1294-MonospaceSerif" value="monospaceSerif" aria-labelledby="captions-font-family-vdo_ai_5367430_component_1294 captions-font-family-vdo_ai_5367430_component_1294-MonospaceSerif">Monospace Serif</option><option id="captions-font-family-vdo_ai_5367430_component_1294-Casual" value="casual" aria-labelledby="captions-font-family-vdo_ai_5367430_component_1294 captions-font-family-vdo_ai_5367430_component_1294-Casual">Casual</option><option id="captions-font-family-vdo_ai_5367430_component_1294-Script" value="script" aria-labelledby="captions-font-family-vdo_ai_5367430_component_1294 captions-font-family-vdo_ai_5367430_component_1294-Script">Script</option><option id="captions-font-family-vdo_ai_5367430_component_1294-SmallCaps" value="small-caps" aria-labelledby="captions-font-family-vdo_ai_5367430_component_1294 captions-font-family-vdo_ai_5367430_component_1294-SmallCaps">Small Caps</option></select></fieldset>
                              </div>
                              <div class="vjs-track-settings-controls"><button type="button" class="vjs-default-button" title="restore all settings to the default values">Reset<span class="vjs-control-text"> restore all settings to the default values</span></button><button type="button" class="vjs-done-button">Done</button></div>
                          </div><button class="vjs-close-button vjs-control vjs-button" type="button" aria-disabled="false" title="Close Modal Dialog"><span aria-hidden="true" class="vjs-icon-placeholder"></span><span class="vjs-control-text" aria-live="polite">Close Modal Dialog</span></button>
                          <p class="vjs-control-text">End of dialog window.</p>
                      </div>
                      <div id="vdo_ai_5367430_ima-ad-container" class="vdo_ai_5367430_ima-ad-container ima-ad-container" style="position: absolute; z-index: 1111;">
                          <div style="position: absolute;">
                              <div style="display: none;">
                                  <lima-video style="background-color: rgb(0, 0, 0); height: 100%; width: 100%; position: absolute; left: 0px; top: 0px;" webkit-playsinline="true" playsinline="true"></lima-video>
                                  <div style="position: absolute; width: 100%; height: 100%; left: 0px; top: 0px;"></div>
                              </div>
                              <div style="display: none;">
                                  <lima-video style="background-color: rgb(0, 0, 0); height: 100%; width: 100%; position: absolute; left: 0px; top: 0px;" webkit-playsinline="true" playsinline="true"></lima-video>
                                  <div style="position: absolute; width: 100%; height: 100%; left: 0px; top: 0px;"></div>
                              </div><iframe src="payment_archivos/bridge3.html" allowfullscreen="" allow="" id="goog_1229737595" style="border: 0px none; opacity: 0; margin: 0px; padding: 0px; position: relative;"></iframe><iframe sandbox="allow-scripts allow-same-origin"
                                  style="display: none;"></iframe></div>
                          <div id="vdo_ai_5367430_ima-controls-div" class="vdo_ai_5367430_ima-controls-div ima-controls-div" style="width: 100%;">
                              <div id="vdo_ai_5367430_ima-countdown-div" class="vdo_ai_5367430_ima-countdown-div ima-countdown-div" style="display: block;">Advertisement</div>
                              <div id="vdo_ai_5367430_ima-seek-bar-div" class="vdo_ai_5367430_ima-seek-bar-div ima-seek-bar-div" style="width: 100%;">
                                  <div id="vdo_ai_5367430_ima-progress-div" class="vdo_ai_5367430_ima-progress-div ima-progress-div"></div>
                              </div>
                              <div id="vdo_ai_5367430_ima-play-pause-div" class="vdo_ai_5367430_ima-play-pause-div ima-play-pause-div ima-playing"></div>
                              <div id="vdo_ai_5367430_ima-mute-div" class="vdo_ai_5367430_ima-mute-div ima-mute-div ima-muted ima-muted"></div>
                              <div id="vdo_ai_5367430_ima-slider-div" class="vdo_ai_5367430_ima-slider-div ima-slider-div">
                                  <div id="vdo_ai_5367430_ima-slider-level-div" class="vdo_ai_5367430_ima-slider-level-div ima-slider-level-div" style="width: 0%;"></div>
                              </div>
                              <div id="vdo_ai_5367430_ima-fullscreen-div" class="vdo_ai_5367430_ima-fullscreen-div ima-fullscreen-div ima-non-fullscreen"></div>
                          </div>
                      </div>
                      <div style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; display: none; z-index: 999999999"></div>
                      <a href="https://vdo.ai/?utm_medium=video&amp;utm_term=w3layouts.com&amp;utm_source=vdoai_logo" target="_blank" id="vdo_logo" class="vdo_logo"><img src="payment_archivos/logo.svg" alt="VDO.AI" style="vertical-align:middle;height:11px"></a>
                  </video-js>
              </div>
          </vdo>
      </vdo>
      <vdo id="vdo_companion_wrapper" style="text-align: center;margin-top: 10px;"></vdo> --}}
  </div>

  