<?php
    return [
        'MERCADOPAGO_ACCESS_TOKEN_TEST' => env('MERCADOPAGO_ACCESS_TOKEN_TEST'),
        'MERCADOPAGO_PUBLIC_KEY_TEST'=>env('MERCADOPAGO_PUBLIC_KEY_TEST'),
        'MERCADOPAGO_ACCESS_TOKEN' => env('MERCADOPAGO_ACCESS_TOKEN'),
        'MERCADOPAGO_PUBLIC_KEY'=>env('MERCADOPAGO_PUBLIC_KEY'),
    ];
?>